In [1]:
import numpy as np

#**Extract**

### Using np.genfromtxt()

In [2]:
data = np.genfromtxt("iot_smart_home.csv",delimiter=",",skip_header=1)   # All datatypes are not preserved

In [3]:
data

array([[  1.        ,          nan,  19.42394318,  60.50035068,
                 nan],
       [  2.        ,          nan,  24.25097122,  73.56588417,
                 nan],
       [  3.        ,          nan,  22.01769343,  34.58328203,
                 nan],
       [  4.        ,          nan,  18.83008372,  23.10175264,
                 nan],
       [  5.        ,          nan,  27.58493833,  62.58458381,
                 nan],
       [  6.        ,          nan,  17.67928804,  77.43585875,
                 nan],
       [  7.        ,          nan,  18.40671256,  21.37011306,
                 nan],
       [  8.        ,          nan,  24.89814669,  74.78855142,
                 nan],
       [  9.        ,          nan,  22.18674368,  63.69642274,
                 nan],
       [ 10.        ,          nan,  16.10171014,  77.32431918,
                 nan],
       [ 11.        ,          nan,  17.08440107,  36.3881269 ,
                 nan],
       [ 12.        ,          nan,  16.684

Option 3: Read as structured array (preserves all data types)  - for mix data types

In [4]:
data = np.genfromtxt("iot_smart_home.csv",delimiter=",",dtype=None,names=True,encoding=None)

In [5]:
data

array([(  1, 'Living Room', 19.42394318, 60.50035068, 'OFF'),
       (  2, 'Living Room', 24.25097122, 73.56588417, 'OFF'),
       (  3, 'Bathroom', 22.01769343, 34.58328203, 'ON'),
       (  4, 'Bedroom', 18.83008372, 23.10175264, 'OFF'),
       (  5, 'Bedroom', 27.58493833, 62.58458381, 'ON'),
       (  6, 'Kitchen', 17.67928804, 77.43585875, 'ON'),
       (  7, 'Living Room', 18.40671256, 21.37011306, 'OFF'),
       (  8, 'Kitchen', 24.89814669, 74.78855142, 'OFF'),
       (  9, 'Bedroom', 22.18674368, 63.69642274, 'OFF'),
       ( 10, 'Kitchen', 16.10171014, 77.32431918, 'OFF'),
       ( 11, 'Kitchen', 17.08440107, 36.3881269 , 'ON'),
       ( 12, 'Bedroom', 16.68460775, 30.23561073, 'ON'),
       ( 13, 'Bedroom', 22.16677448, 39.35606107, 'OFF'),
       ( 14, 'Kitchen', 23.10444344, 36.63430765, 'OFF'),
       ( 15, 'Bathroom', 29.37106574, 49.43614718, 'OFF'),
       ( 16, 'Kitchen', 23.75688467, 27.84294478, 'ON'),
       ( 17, 'Bathroom', 22.89996137, 64.29102419, 'OFF'),
     

In [6]:
type(data)

numpy.ndarray

In [7]:
np.ndim(data)

1

### Using np.loadtxt()

In [8]:
data_load = np.loadtxt(
    "iot_smart_home.csv",
    delimiter=",",
    skiprows=1, #Header row
    dtype=[
        ('Sensor_ID',int),
        ('Room','U20'),  #Unicode max length of 20
        ('Temperature_C',float),
        ('Humidity_%',float),
        ('Appliance_Status','U5') #Unicode for On/OFF
    ],
    encoding=None)

In [9]:
data_load

array([(  1, 'Living Room', 19.42394318, 60.50035068, 'OFF'),
       (  2, 'Living Room', 24.25097122, 73.56588417, 'OFF'),
       (  3, 'Bathroom', 22.01769343, 34.58328203, 'ON'),
       (  4, 'Bedroom', 18.83008372, 23.10175264, 'OFF'),
       (  5, 'Bedroom', 27.58493833, 62.58458381, 'ON'),
       (  6, 'Kitchen', 17.67928804, 77.43585875, 'ON'),
       (  7, 'Living Room', 18.40671256, 21.37011306, 'OFF'),
       (  8, 'Kitchen', 24.89814669, 74.78855142, 'OFF'),
       (  9, 'Bedroom', 22.18674368, 63.69642274, 'OFF'),
       ( 10, 'Kitchen', 16.10171014, 77.32431918, 'OFF'),
       ( 11, 'Kitchen', 17.08440107, 36.3881269 , 'ON'),
       ( 12, 'Bedroom', 16.68460775, 30.23561073, 'ON'),
       ( 13, 'Bedroom', 22.16677448, 39.35606107, 'OFF'),
       ( 14, 'Kitchen', 23.10444344, 36.63430765, 'OFF'),
       ( 15, 'Bathroom', 29.37106574, 49.43614718, 'OFF'),
       ( 16, 'Kitchen', 23.75688467, 27.84294478, 'ON'),
       ( 17, 'Bathroom', 22.89996137, 64.29102419, 'OFF'),
     

#**Extract**

Another Smart Home Dataset

In [36]:
data_smart_home = np.genfromtxt(
    "smart_home_dataset.csv",
    delimiter = ',',
    names=True,
    dtype = None,
    encoding='utf-8'
)

In [37]:
data_smart_home

array([(1577836800,     1, 0, 0, 0, 1, 0, 237, 233, 1559, 24.00176259, 'January', 'Wednesday',  0, 'Local'),
       (1577839322,     2, 0, 1, 0, 0, 1, 232, 230, 1970, 31.22515417, 'January', 'Wednesday',  0, 'Remote'),
       (1577841845,     3, 0, 1, 0, 0, 0, 223, 222, 1684, 70.4607001 , 'January', 'Wednesday',  1, 'Remote'),
       ...,
       (1701382181, 48970, 1, 0, 0, 1, 1, 235, 229, 1686, 40.22409706, 'November', 'Thursday', 22, 'Local'),
       (1701384704, 48971, 1, 1, 1, 1, 1, 237, 230, 1754, 37.3663604 , 'November', 'Thursday', 22, 'Local'),
       (1701387227, 48972, 0, 0, 0, 0, 1, 220, 215, 1660, 66.23906544, 'November', 'Thursday', 23, 'Local')],
      dtype=[('Unix_Timestamp', '<i8'), ('Transaction_ID', '<i8'), ('Television', '<i8'), ('Dryer', '<i8'), ('Oven', '<i8'), ('Refrigerator', '<i8'), ('Microwave', '<i8'), ('Line_Voltage', '<i8'), ('Voltage', '<i8'), ('Apparent_Power', '<i8'), ('Energy_Consumption_kWh', '<f8'), ('Month', '<U9'), ('Day_of_the_Week', '<U9'), ('Hour

#**Transform**

###**Parse timestamps to Numpy datetime64**

In [38]:
data_smart_home['Unix_Timestamp']

array([1577836800, 1577839322, 1577841845, ..., 1701382181, 1701384704,
       1701387227])

In [39]:
timestamps = data_smart_home['Unix_Timestamp'].astype('datetime64[s]')

In [40]:
timestamps  #np arrays are immutable so this will not be replaced inside the data_smart_home array

array(['2020-01-01T00:00:00', '2020-01-01T00:42:02',
       '2020-01-01T01:24:05', ..., '2023-11-30T22:09:41',
       '2023-11-30T22:51:44', '2023-11-30T23:33:47'],
      dtype='datetime64[s]')

###**Combine with sensor measurements:**

In [43]:
#sensor_cols = [col for col in data_smart_home.dtype.names if col !='Unix_Timestamp']
sensor_cols = [
    'Transaction_ID','Television', 'Dryer', 'Oven', 'Refrigerator', 'Microwave',
    'Line_Voltage', 'Voltage', 'Apparent_Power', 'Energy_Consumption_kWh','Hour_of_the_Day'
]

In [44]:
values = np.vstack([data_smart_home[col].astype(float) for col in sensor_cols]).T
values

array([[1.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        1.55900000e+03, 2.40017626e+01, 0.00000000e+00],
       [2.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.97000000e+03, 3.12251542e+01, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.68400000e+03, 7.04607001e+01, 1.00000000e+00],
       ...,
       [4.89700000e+04, 1.00000000e+00, 0.00000000e+00, ...,
        1.68600000e+03, 4.02240971e+01, 2.20000000e+01],
       [4.89710000e+04, 1.00000000e+00, 1.00000000e+00, ...,
        1.75400000e+03, 3.73663604e+01, 2.20000000e+01],
       [4.89720000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        1.66000000e+03, 6.62390654e+01, 2.30000000e+01]])

###**Define sampling windows (e.g., hourly):**

In [25]:
timestamps

array(['2020-01-01T00:00:00', '2020-01-01T00:42:02',
       '2020-01-01T01:24:05', ..., '2023-11-30T22:09:41',
       '2023-11-30T22:51:44', '2023-11-30T23:33:47'],
      dtype='datetime64[s]')

In [26]:
timestamps[0]

np.datetime64('2020-01-01T00:00:00')

In [27]:
start = timestamps[0].astype('datetime64[h]')
start

np.datetime64('2020-01-01T00','h')

In [28]:
end = timestamps[-1].astype('datetime64[h]')
end

np.datetime64('2023-11-30T23','h')

In [29]:
hours = np.arange(start,end + 1,dtype='datetime64[h]')
hours

array(['2020-01-01T00', '2020-01-01T01', '2020-01-01T02', ...,
       '2023-11-30T21', '2023-11-30T22', '2023-11-30T23'],
      dtype='datetime64[h]')

###**Compute hourly aggregates per sensor:**



In [32]:
timestamps[:10]

array(['2020-01-01T00:00:00', '2020-01-01T00:42:02',
       '2020-01-01T01:24:05', '2020-01-01T02:06:08',
       '2020-01-01T02:48:11', '2020-01-01T03:30:14',
       '2020-01-01T04:12:17', '2020-01-01T04:54:20',
       '2020-01-01T05:36:23', '2020-01-01T06:18:26'],
      dtype='datetime64[s]')

In [33]:
hours[:10]

array(['2020-01-01T00', '2020-01-01T01', '2020-01-01T02', '2020-01-01T03',
       '2020-01-01T04', '2020-01-01T05', '2020-01-01T06', '2020-01-01T07',
       '2020-01-01T08', '2020-01-01T09'], dtype='datetime64[h]')

**Elementwise BroadCasting**

In [30]:
means = []
for i in range(10):
    mask = (timestamps >= hours[i]) & (timestamps < hours[i+1])
    print(mask)
    chunk = values[mask]
    print(chunk)
    #means.append(np.nanmean(chunk, axis=0))

[ True  True False ... False False False]
[['1' '0' '0' '0' '1' '0' '237' '233' '1559' '24.00176259' 'January'
  'Wednesday' '0' 'Local']
 ['2' '0' '1' '0' '0' '1' '232' '230' '1970' '31.22515417' 'January'
  'Wednesday' '0' 'Remote']]
[False False  True ... False False False]
[['3' '0' '1' '0' '0' '0' '223' '222' '1684' '70.4607001' 'January'
  'Wednesday' '1' 'Remote']]
[False False False ... False False False]
[['4' '1' '0' '1' '1' '0' '225' '224' '1694' '32.26404281' 'January'
  'Wednesday' '2' 'Remote']
 ['5' '1' '0' '0' '1' '0' '222' '214' '1889' '32.72811106' 'January'
  'Wednesday' '2' 'Local']]
[False False False ... False False False]
[['6' '0' '1' '0' '1' '0' '235' '227' '1503' '63.9384203' 'January'
  'Wednesday' '3' 'Local']]
[False False False ... False False False]
[['7' '0' '1' '0' '0' '1' '237' '237' '1739' '87.59288954' 'January'
  'Wednesday' '4' 'Local']
 ['8' '0' '1' '1' '1' '0' '235' '227' '1996' '37.7962616' 'January'
  'Wednesday' '4' 'Local']]
[False False Fals

In [45]:
means = []
for i in range(len(hours)-1):
    mask = (timestamps >= hours[i]) & (timestamps < hours[i+1])
    #print(mask)
    chunk = values[mask]
    #print(chunk)
    means.append(np.nanmean(chunk, axis=0))

In [46]:
means

[array([1.50000000e+00, 0.00000000e+00, 5.00000000e-01, 0.00000000e+00,
        5.00000000e-01, 5.00000000e-01, 2.34500000e+02, 2.31500000e+02,
        1.76450000e+03, 2.76134584e+01, 0.00000000e+00]),
 array([3.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.23000000e+02, 2.22000000e+02,
        1.68400000e+03, 7.04607001e+01, 1.00000000e+00]),
 array([4.50000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        1.00000000e+00, 0.00000000e+00, 2.23500000e+02, 2.19000000e+02,
        1.79150000e+03, 3.24960769e+01, 2.00000000e+00]),
 array([6.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.35000000e+02, 2.27000000e+02,
        1.50300000e+03, 6.39384203e+01, 3.00000000e+00]),
 array([7.50000000e+00, 0.00000000e+00, 1.00000000e+00, 5.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 2.36000000e+02, 2.32000000e+02,
        1.86750000e+03, 6.26945756e+01, 4.000000

In [47]:
hourly_means = np.array(means)

In [48]:
hourly_means

array([[1.50000000e+00, 0.00000000e+00, 5.00000000e-01, ...,
        1.76450000e+03, 2.76134584e+01, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.68400000e+03, 7.04607001e+01, 1.00000000e+00],
       [4.50000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.79150000e+03, 3.24960769e+01, 2.00000000e+00],
       ...,
       [4.89675000e+04, 1.00000000e+00, 0.00000000e+00, ...,
        1.87650000e+03, 1.77320734e+01, 2.00000000e+01],
       [4.89690000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        1.69200000e+03, 9.19653426e+01, 2.10000000e+01],
       [4.89705000e+04, 1.00000000e+00, 5.00000000e-01, ...,
        1.72000000e+03, 3.87952287e+01, 2.20000000e+01]])

###**Detect and handle outliers using Z-score:**

In [49]:
mean = np.nanmean(hourly_means, axis=0)
std = np.nanstd(hourly_means, axis=0)
z = (hourly_means - mean) / std
hourly_means[np.abs(z) > 3] = np.nan  # Mark as invalid

In [51]:
hourly_means

array([[1.50000000e+00, 0.00000000e+00, 5.00000000e-01, ...,
        1.76450000e+03, 2.76134584e+01, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 1.00000000e+00, ...,
        1.68400000e+03, 7.04607001e+01, 1.00000000e+00],
       [4.50000000e+00, 1.00000000e+00, 0.00000000e+00, ...,
        1.79150000e+03, 3.24960769e+01, 2.00000000e+00],
       ...,
       [4.89675000e+04, 1.00000000e+00, 0.00000000e+00, ...,
        1.87650000e+03, 1.77320734e+01, 2.00000000e+01],
       [4.89690000e+04, 0.00000000e+00, 0.00000000e+00, ...,
        1.69200000e+03, 9.19653426e+01, 2.10000000e+01],
       [4.89705000e+04, 1.00000000e+00, 5.00000000e-01, ...,
        1.72000000e+03, 3.87952287e+01, 2.20000000e+01]])

#**LOAD**

###**Save cleaned data:**

In [50]:
np.save("sensor_hourly_means.npy",hourly_means)

#**View the file**

In [53]:
hour_mean = np.load("sensor_hourly_means.npy")

In [54]:
hour_mean[:5]

array([[1.50000000e+00, 0.00000000e+00, 5.00000000e-01, 0.00000000e+00,
        5.00000000e-01, 5.00000000e-01, 2.34500000e+02, 2.31500000e+02,
        1.76450000e+03, 2.76134584e+01, 0.00000000e+00],
       [3.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 2.23000000e+02, 2.22000000e+02,
        1.68400000e+03, 7.04607001e+01, 1.00000000e+00],
       [4.50000000e+00, 1.00000000e+00, 0.00000000e+00, 5.00000000e-01,
        1.00000000e+00, 0.00000000e+00, 2.23500000e+02, 2.19000000e+02,
        1.79150000e+03, 3.24960769e+01, 2.00000000e+00],
       [6.00000000e+00, 0.00000000e+00, 1.00000000e+00, 0.00000000e+00,
        1.00000000e+00, 0.00000000e+00, 2.35000000e+02, 2.27000000e+02,
        1.50300000e+03, 6.39384203e+01, 3.00000000e+00],
       [7.50000000e+00, 0.00000000e+00, 1.00000000e+00, 5.00000000e-01,
        5.00000000e-01, 5.00000000e-01, 2.36000000e+02, 2.32000000e+02,
        1.86750000e+03, 6.26945756e+01, 4.00000000e+